language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0


before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

script:
  - XDEBUG_MODE=coverage php composer.phar test -- --coverage --coverage-xml

after_script:
  - php vendor/bin/codacycoverage clover tests/_output/build/coverage/xml